spring:
  mail:
    password:
    port: 587
    host: smtp.gmail.com
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
        debug: true
        transport:
          protocol: smtp
    username: rashadjavad@gmail.com
  datasource:
    password:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true